name: "Sync GHAS to Jira"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes
permissions:
  contents: read
  security-events: write
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://baaskit.atlassian.net'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'BIS'
          sync_direction: 'gh2jira'
